[project]
name = "dir-upload"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.5"
dependencies = [
    "pandas>=2.3.0",
    "rich>=14.0.0",
    "xlsxwriter>=3.2.5",
    "xlwings>=0.33.15",
]
